title:    Matthew Arucan
logo: /assets/images/headshot_photo.png
description: ğŸ” Data Analyst | Business Analyst | SQL, Microsoft Excel, Python, Tableau | Turning Data Into Insights
show_downloads: true
theme: jekyll-theme-minimal
