title:    Matthew Arucan
logo: /assets/images/headshot_photo.png
description: Data Analyst|Business Analyst|Analytics, SQL, Excel, Tableau, Power BI, Python
show_downloads: true
theme: jekyll-theme-minimal
